authorName: DafnaMagid
experimentName: Dafna NNI GDM
trialConcurrency: 4
maxExecDuration: 300h
maxTrialNum: 99999
trainingServicePlatform: local
searchSpacePath: multi_bacteria_params.json
useAnnotation: false
tuner:
  builtinTunerName: TPE
  classArgs:
    optimize_mode: minimize
trial:
  command: python multi_bacteria_nni_runner.py
  codeDir: .
  gpuNum: 1
localConfig:
  maxTrialNumPerGpu: 1
  useActiveGpu: True