authorName: Yoel
experimentName: Yoel NNI GDM
trialConcurrency: 4
maxExecDuration: 1h
maxTrialNum: 100
trainingServicePlatform: local

# The path to Search Space
#searchSpacePath: search_space2.json
searchSpacePath: params.json
useAnnotation: false
tuner:
#  builtinTunerName: GridSearch
  builtinTunerName: TPE
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize
# The path and the running command of trial
trial:
  command: python NNI.py
  codeDir: .
  gpuNum: 0
localConfig:
  # gpuIndices: 1,2
  maxTrialNumPerGpu: 1
  useActiveGpu: false